// const countryList = {
//     AED: "AE",
//     AFN: "AF",
//     XCD: "AG",
//     ALL: "AL",
//     AMD: "AM",
//     ANG: "AN",
//     AOA: "AO",
//     AQD: "AQ",
//     ARS: "AR",
//     AUD: "AU",
//     AZN: "AZ",
//     BAM: "BA",
//     BBD: "BB",
//     BDT: "BD",
//     XOF: "BE",
//     BGN: "BG",
//     BHD: "BH",
//     BIF: "BI",
//     BMD: "BM",
//     BND: "BN",
//     BOB: "BO",
//     BRL: "BR",
//     BSD: "BS",
//     NOK: "BV",
//     BWP: "BW",
//     BYR: "BY",
//     BZD: "BZ",
//     CAD: "CA",
//     CDF: "CD",
//     XAF: "CF",
//     CHF: "CH",
//     CLP: "CL",
//     CNY: "CN",
//     COP: "CO",
//     CRC: "CR",
//     CUP: "CU",
//     CVE: "CV",
//     CYP: "CY",
//     CZK: "CZ",
//     DJF: "DJ",
//     DKK: "DK",
//     DOP: "DO",
//     DZD: "DZ",
//     ECS: "EC",
//     EEK: "EE",
//     EGP: "EG",
//     ETB: "ET",
//     EUR: "FR",
//     FJD: "FJ",
//     FKP: "FK",
//     GBP: "GB",
//     GEL: "GE",
//     GGP: "GG",
//     GHS: "GH",
//     GIP: "GI",
//     GMD: "GM",
//     GNF: "GN",
//     GTQ: "GT",
//     GYD: "GY",
//     HKD: "HK",
//     HNL: "HN",
//     HRK: "HR",
//     HTG: "HT",
//     HUF: "HU",
//     IDR: "ID",
//     ILS: "IL",
//     INR: "IN",
//     IQD: "IQ",
//     IRR: "IR",
//     ISK: "IS",
//     JMD: "JM",
//     JOD: "JO",
//     JPY: "JP",
//     KES: "KE",
//     KGS: "KG",
//     KHR: "KH",
//     KMF: "KM",
//     KPW: "KP",
//     KRW: "KR",
//     KWD: "KW",
//     KYD: "KY",
//     KZT: "KZ",
//     LAK: "LA",
//     LBP: "LB",
//     LKR: "LK",
//     LRD: "LR",
//     LSL: "LS",
//     LTL: "LT",
//     LVL: "LV",
//     LYD: "LY",
//     MAD: "MA",
//     MDL: "MD",
//     MGA: "MG",
//     MKD: "MK",
//     MMK: "MM",
//     MNT: "MN",
//     MOP: "MO",
//     MRO: "MR",
//     MTL: "MT",
//     MUR: "MU",
//     MVR: "MV",
//     MWK: "MW",
//     MXN: "MX",
//     MYR: "MY",
//     MZN: "MZ",
//     NAD: "NA",
//     XPF: "NC",
//     NGN: "NG",
//     NIO: "NI",
//     NPR: "NP",
//     NZD: "NZ",
//     OMR: "OM",
//     PAB: "PA",
//     PEN: "PE",
//     PGK: "PG",
//     PHP: "PH",
//     PKR: "PK",
//     PLN: "PL",
//     PYG: "PY",
//     QAR: "QA",
//     RON: "RO",
//     RSD: "RS",
//     RUB: "RU",
//     RWF: "RW",
//     SAR: "SA",
//     SBD: "SB",
//     SCR: "SC",
//     SDG: "SD",
//     SEK: "SE",
//     SGD: "SG",
//     SKK: "SK",
//     SLL: "SL",
//     SOS: "SO",
//     SRD: "SR",
//     STD: "ST",
//     SVC: "SV",
//     SYP: "SY",
//     SZL: "SZ",
//     THB: "TH",
//     TJS: "TJ",
//     TMT: "TM",
//     TND: "TN",
//     TOP: "TO",
//     TRY: "TR",
//     TTD: "TT",
//     TWD: "TW",
//     TZS: "TZ",
//     UAH: "UA",
//     UGX: "UG",
//     USD: "US",
//     UYU: "UY",
//     UZS: "UZ",
//     VEF: "VE",
//     VND: "VN",
//     VUV: "VU",
//     YER: "YE",
//     ZAR: "ZA",
//     ZMK: "ZM",
//     ZWD: "ZW",
//   };












const countryList = {
  AE: "AE",
  AF: "AF",
  AG: "AG",
  AL: "AL",
  AM: "AM",
  AO: "AO",
  AR: "AR",
  AU: "AU",
  AZ: "AZ",
  BA: "BA",
  BB: "BB",
  BD: "BD",
  BE: "BE",
  BG: "BG",
  BH: "BH",
  BI: "BI",
  BM: "BM",
  BN: "BN",
  BO: "BO",
  BR: "BR",
  BS: "BS",
  BW: "BW",
  BY: "BY",
  BZ: "BZ",
  CA: "CA",
  CD: "CD",
  CF: "CF",
  CH: "CH",
  CL: "CL",
  CN: "CN",
  CO: "CO",
  CR: "CR",
  CU: "CU",
  CV: "CV",
  CY: "CY",
  CZ: "CZ",
  DE: "DE",
  DJ: "DJ",
  DK: "DK",
  DO: "DO",
  DZ: "DZ",
  EC: "EC",
  EE: "EE",
  EG: "EG",
  ES: "ES",
  ET: "ET",
  FI: "FI",
  FJ: "FJ",
  FM: "FM",
  FR: "FR",
  GA: "GA",
  GB: "GB",
  GE: "GE",
  GH: "GH",
  GL: "GL",
  GM: "GM",
  GN: "GN",
  GQ: "GQ",
  GR: "GR",
  GT: "GT",
  GW: "GW",
  GY: "GY",
  HK: "HK",
  HN: "HN",
  HR: "HR",
  HT: "HT",
  HU: "HU",
  ID: "ID",
  IE: "IE",
  IL: "IL",
  IN: "IN",
  IQ: "IQ",
  IR: "IR",
  IS: "IS",
  IT: "IT",
  JM: "JM",
  JO: "JO",
  JP: "JP",
  KE: "KE",
  KG: "KG",
  KH: "KH",
  KI: "KI",
  KM: "KM",
  KN: "KN",
  KP: "KP",
  KR: "KR",
  KW: "KW",
  KZ: "KZ",
  LA: "LA",
  LB: "LB",
  LC: "LC",
  LI: "LI",
  LK: "LK",
  LR: "LR",
  LS: "LS",
  LT: "LT",
  LU: "LU",
  LV: "LV",
  LY: "LY",
  MA: "MA",
  MC: "MC",
  MD: "MD",
  ME: "ME",
  MG: "MG",
  MH: "MH",
  MK: "MK",
  ML: "ML",
  MM: "MM",
  MN: "MN",
  MR: "MR",
  MT: "MT",
  MU: "MU",
  MV: "MV",
  MW: "MW",
  MX: "MX",
  MY: "MY",
  MZ: "MZ",
  NA: "NA",
  NE: "NE",
  NG: "NG",
  NI: "NI",
  NL: "NL",
  NO: "NO",
  NP: "NP",
  NR: "NR",
  NZ: "NZ",
  OM: "OM",
  PA: "PA",
  PE: "PE",
  PG: "PG",
  PH: "PH",
  PK: "PK",
  PL: "PL",
  PT: "PT",
  PW: "PW",
  PY: "PY",
  QA: "QA",
  RO: "RO",
  RS: "RS",
  RU: "RU",
  RW: "RW",
  SA: "SA",
  SB: "SB",
  SC: "SC",
  SD: "SD",
  SE: "SE",
  SG: "SG",
  SI: "SI",
  SK: "SK",
  SL: "SL",
  SM: "SM",
  SN: "SN",
  SO: "SO",
  SR: "SR",
  ST: "ST",
  SV: "SV",
  SY: "SY",
  SZ: "SZ",
  TD: "TD",
  TG: "TG",
  TH: "TH",
  TJ: "TJ",
  TL: "TL",
  TM: "TM",
  TN: "TN",
  TO: "TO",
  TR: "TR",
  TT: "TT",
  TV: "TV",
  TZ: "TZ",
  UA: "UA",
  UG: "UG",
  US: "US",
  UY: "UY",
  UZ: "UZ",
  VA: "VA",
  VC: "VC",
  VE: "VE",
  VN: "VN",
  VU: "VU",
  WS: "WS",
  YE: "YE",
  ZA: "ZA",
  ZM: "ZM",
  ZW: "ZW"
};
